[package]
name = "flyweight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "flyweight"
path = "src/main.rs"
[dependencies]
draw = "0.3"
memory-stats = "1.0.0"
rand = "0.8"
